CREATE TABLE "flights" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" text DEFAULT 'default' NOT NULL,
	"flight_date" date NOT NULL,
	"aircraft_make_model" text NOT NULL,
	"registration" text NOT NULL,
	"pilot_in_command" text,
	"copilot_or_student" text,
	"departure_airport" text,
	"arrival_airport" text,
	"remarks" text,
	"se_day_dual" real,
	"se_day_pic" real,
	"se_day_copilot" real,
	"se_night_dual" real,
	"se_night_pic" real,
	"se_night_copilot" real,
	"me_day_dual" real,
	"me_day_pic" real,
	"me_day_copilot" real,
	"me_night_dual" real,
	"me_night_pic" real,
	"me_night_copilot" real,
	"xc_day_dual" real,
	"xc_day_pic" real,
	"xc_day_copilot" real,
	"xc_night_dual" real,
	"xc_night_pic" real,
	"xc_night_copilot" real,
	"day_takeoffs_landings" integer,
	"night_takeoffs_landings" integer,
	"actual_imc" real,
	"hood" real,
	"simulator" real,
	"ifr_approaches" integer,
	"holding" integer,
	"as_flight_instructor" real,
	"dual_received" real,
	"time_on" text,
	"time_off" text,
	"total_duty" real,
	"flight_hours" real NOT NULL,
	"imported_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
